### ISSUE TITLE
[SUGGESTION] Compat with a few mods

### ISSUE THREAD

**Issue by Sunconure11** [EmilsGithub/Backported-Wolves#2]
https://www.curseforge.com/minecraft/mc-mods/woof

https://www.curseforge.com/minecraft/mc-mods/wolf-armor-compat

https://www.curseforge.com/minecraft/mc-mods/wolves-with-armor

These three mods could go with some compat with your mod

**Comment by EmilsGithub** [comment]
Wolves With Armor already works, Wolf Armor Compat is just more versions of the armors.
![2024-03-13_00 07 09](https://github.com/EmilsGithub/Backported-Wolves/assets/88748435/18c78b25-3914-4840-a22c-8562ff34fe5a)
WOOF compat would require extensive work from both me and the developer of that mod.
